# Site settings
title: Descendant
email: descendant@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Get to know your descendance
baseurl: "" # the subpath of your site, e.g. /newpath-for-emping
url: "https://descendant.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  descendant
GoogleAnalytics: UA-xxxxxx-x

twitter:
  username: rmsubekti
facebook:
  app_id: 1234567
  publisher: 1234567

sass:
    style: compressed

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true

gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

defaults:
    - {scope: {type: posts}, values: {layout: post, permalink: '/blog/:title'}}

include:
  - _pages

exclude:
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock

paginate: 12
paginate_path: '/blog/:num'
